### ISSUE TITLE
docker-credential-gcr doesn't work

### ISSUE THREAD

**Issue by raylu** [buildbuddy-io/buildbuddy-helm#65]
the image configures the GCR cred helper here https://github.com/buildbuddy-io/buildbuddy/blob/5a07a454d8003ecfe507c076cce477186e865dc5/dockerfiles/executor_image/Dockerfile#L37

but that writes to `$HOME/.config/docker/auth.json`, which at build time resolves to `/root/.config/docker/auth.json`

later, the helm chart comes along and sets `HOME` to `/buildbuddy` https://github.com/buildbuddy-io/buildbuddy-helm/blob/79753a73c9bb459cb0aa0809b9550a29dc9d2e22/charts/buildbuddy-executor/templates/deployment.yaml#L86-L87

so docker/podman don't find the `auth.json`

it's also not possible to fix this by building a new image because `/buildbuddy` is a bind mount
https://github.com/buildbuddy-io/buildbuddy-helm/blob/79753a73c9bb459cb0aa0809b9550a29dc9d2e22/charts/buildbuddy-executor/templates/deployment.yaml#L128-L129

**Comment by sluongng** [comment]
This is a regression caused by my change in https://github.com/buildbuddy-io/buildbuddy-helm/commit/60e7116ce5dfdd5eb45e681a31062c63a1e315e3. 

> Set $HOME=/buildbuddy to retain the .config/buildbuddy/host_id between accidental container restarts.

This was a reactionary fix for folks who wish to retain the same data between container restarts within the same pod.
This rarely happens, but in some self-hosted setups, folks do run into such edge cases more often than usual.

I think the correct solution should be to turn `$HOME/.config/buildbuddy/` into a bind mount, with `$HOME == root`.
Let me discuss this with my team and get back to you on this.
